<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJjygacm\EccubeProProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJjygacm/EccubeProProjectContainer.php') {
    touch(__DIR__.'/ContainerJjygacm.legacy');

    return;
}

if (!\class_exists(EccubeProProjectContainer::class, false)) {
    \class_alias(\ContainerJjygacm\EccubeProProjectContainer::class, EccubeProProjectContainer::class, false);
}

return new \ContainerJjygacm\EccubeProProjectContainer([
    'container.build_hash' => 'Jjygacm',
    'container.build_id' => '9b2664eb',
    'container.build_time' => 1621845297,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJjygacm');
