<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\CustomerRank\Repository\CustomerSalonCodeRepository' shared autowired service.

include_once $this->targetDirs[3].'\\app\\Plugin\\CustomerRank\\Repository\\CustomerSalonCodeRepository.php';

return $this->services['Plugin\\CustomerRank\\Repository\\CustomerSalonCodeRepository'] = new \Plugin\CustomerRank\Repository\CustomerSalonCodeRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, 'Plugin\\CustomerRank\\Entity\\CustomerSalonCode', ${($_ = isset($this->services['security.helper']) ? $this->services['security.helper'] : $this->load('getSecurity_HelperService.php')) && false ?: '_'});
