<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\CustomerRank\Form\Type\Admin\CustomerSalonCodeType' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormTypeInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\AbstractType.php';
include_once $this->targetDirs[3].'\\app\\Plugin\\CustomerRank\\Form\\Type\\Admin\\CustomerSalonCodeType.php';

return $this->services['Plugin\\CustomerRank\\Form\\Type\\Admin\\CustomerSalonCodeType'] = new \Plugin\CustomerRank\Form\Type\Admin\CustomerSalonCodeType(${($_ = isset($this->services['Eccube\\Repository\\MemberRepository']) ? $this->services['Eccube\\Repository\\MemberRepository'] : $this->load('getMemberRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.helper']) ? $this->services['security.helper'] : $this->load('getSecurity_HelperService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['security.authorization_checker']) ? $this->services['security.authorization_checker'] : $this->getSecurity_AuthorizationCheckerService()) && false ?: '_'});
