<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\CustomerRank\Form\Validator\DuplicateSalonCodeValidator' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\validator\\ConstraintValidatorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\validator\\ConstraintValidator.php';
include_once $this->targetDirs[3].'\\app\\Plugin\\CustomerRank\\Form\\Validator\\DuplicateSalonCodeValidator.php';

return $this->services['Plugin\\CustomerRank\\Form\\Validator\\DuplicateSalonCodeValidator'] = new \Plugin\CustomerRank\Form\Validator\DuplicateSalonCodeValidator(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
