<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3xvcr67\EccubeDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3xvcr67/EccubeDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3xvcr67.legacy');

    return;
}

if (!\class_exists(EccubeDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3xvcr67\EccubeDevDebugProjectContainer::class, EccubeDevDebugProjectContainer::class, false);
}

return new \Container3xvcr67\EccubeDevDebugProjectContainer([
    'container.build_hash' => '3xvcr67',
    'container.build_id' => 'b5b50ab7',
    'container.build_time' => 1621845050,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3xvcr67');
